version: "3"

services:
  database:
    image: mysql:5.7
    restart: always
    container_name: mysql
    volumes:
      - mysql-volumes:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mysql-volumes:
